### PR TITLE
[#115] Add ExceptionHandler interface that users can customize exception handler

### LINKED ISSUE #115: Add ExceptionHandler interface that users can customize exception handler
Currently, the users with dss cannot handle exceptions.

So, I suggest adding the exception handler.

```java
public class Application{
    public static void main() throws InterruptedException {
        DssRestServer dssRestServer = new DssRestServer("127.0.0.1", 8181);
        dssRestServer
                .addDssService(new MyService())
                .addExceptionHandler(new GlobalExceptionHandler());

        dssRestServer.start();
    }
}

public class GlobalExceptionHandler implements DssServiceExceptionHandler {
    // to handle all NullpointerException
    @ExceptionHandler(exception = NullPointerException.class)
    public DssRestServiceResponse nullPointerExceptionHandler(DssRestServiceRequest request) {
        System.out.println("Global nullPointerExceptionHandler");

        return new Response("To handle nullPointerException");
    }

    // to handle IOException only on myservice
    @ServiceExceptionHandler(service = MyService.class, exception = IOException.class)
    public void serviceExceptionHandler() {
        System.out.println("IOException in my service");
    }
}

```
like this.

### PR DESCRIPTION
**Pull request by Alencion**
## Description
I try to implement customExceptionHandler feature. 

like this. 
### 1. definition Exception Handler
``` java
public class GlobalExceptionHandler implements DssExceptionHandler {
     // global exception handle method
    @ExceptionHandler(exception = NullPointerException.class)
    public YourServiceResponse globalExceptionHandleMethod(){
        YourServiceResponse yourServiceResponse = new YourServiceResponse();
        yourServiceResponse.setResult("Handle Exception on globalExceptionHandlerMethod");
        return yourServiceResponse;
    }

    // service exception handler method
    @ServiceExceptionHandler(service = MyService.class, exception = NullPointerException.class)
    public MyServiceResponse serviceExceptionHandleMethod(MyServiceRequest request){
        MyServiceResponse myServiceResponse = new MyServiceResponse();
        myServiceResponse.setResult("Occur NullPointer Exception in MyService." + " request: " + request.getName());
        return myServiceResponse;
    }
}
```

### 2. add exception handler 
```java
publicclass Application {

    @Test
    public static void main() throws InterruptedException {
        final DssRestServer dssRestServer = new DssRestServer("127.0.0.1", 8181);
        dssRestServer
                .addDssService(new MyService())
                .addDssService(new YourService())
                .addExceptionHandler(new GlobalExceptionHandler());

        dssRestServer.start();
    }
}
```

### 3. handling exception
global
image

service
image

---
##  What i want a review point

1. method, variable name etc.
2. Whether I created the java file in the right package or not.
3. if DssRestRequestMappingException occur, The exception handle method with request parameter does't execute. What do you think this situation?
4. anything else.

### CODE REVIEW

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+import io.github.ztkmkoo.dss.core.actor.rest.service.DssRestActorService;
+import lombok.Builder;
+import lombok.Getter;
+
+@Getter
+public class DssRestExceptionHandlerCommandRequest implements DssRestExceptionHandlerCommand {
+    private static final long serialVersionUID = 5752260184738368572L;
+
+    private final DssRestActorService service;
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java]: It looks transient(not serializable)?
If yes, please add the keyword

File: dss-server/src/main/java/io/github/ztkmkoo/dss/server/DssServer.java [hunk 2]
```diff
@@ -38,4 +39,6 @@
      * @return self(for method chain)
      */
     DssServer<S> addDssService(S service);
+
+    DssServer<S> addExceptionHandler(DssExceptionHandler exceptionHandler);
```
Comment (ztkmkoo) [inline dss-server/src/main/java/io/github/ztkmkoo/dss/server/DssServer.java:47]: Could you like to add the document of this method?

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+
+        return null;
+    }
+
+    private DssRestServiceResponse invokeMethod(Method method, DssRestExceptionHandlerCommandRequest commandRequest) {
+        try {
+            Constructor<?> declaredConstructor = method.getDeclaringClass().getDeclaredConstructor();
+            declaredConstructor.setAccessible(true);
+
+            Object exceptionHandler = declaredConstructor.newInstance();
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: Do i have to generate new exception handler instance every exception handling?

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+                response = method.invoke(exceptionHandler, request.getBody());
+            } else {
+                response = method.invoke(exceptionHandler, null);
+            }
+
+            if (response instanceof DssRestServiceResponse) {
+                return (DssRestServiceResponse) response;
+            }
+        } catch (InstantiationException | InvocationTargetException | NoSuchMethodException | IllegalAccessException e) {
+            e.printStackTrace();
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: Please use logger instead of printStackTrace

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+            declaredConstructor.setAccessible(true);
+
+            Object exceptionHandler = declaredConstructor.newInstance();
+            Object response;
+
+            if (method.getParameterCount() == 1){
+                Method makeRequest = AbstractDssRestActorService.class.getDeclaredMethod("makeRequest", DssRestServiceActorCommandRequest.class);
+                makeRequest.setAccessible(true);
+
+                DssRestServiceRequest request = (DssRestServiceRequest) makeRequest.invoke(commandRequest.getService(), commandRequest.getRequest());
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: Is it the best way to get the service request?

**Comment by ztkmkoo** [comment]
@Alencion 
Is it necessary using reflection in exception handling actor?
I want to talk bout with you~~

File: dss-server/src/main/java/io/github/ztkmkoo/dss/server/DssServer.java (hunk 2 above)
Comment (Alencion) [reply dss-server/src/main/java/io/github/ztkmkoo/dss/server/DssServer.java:47]: Ok. I will add document.

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java (hunk 3 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: I think it just need one. I didn't think about this. Thank you.

I try to code an instance of exceptionHandler to create once.

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java (hunk 1 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java]: Thank you for review! 

I couldn't understand your opinion. Could you explain more detail?

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java (hunk 5 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: if this method's access modifier may be changed to public,
it seems possible like the next code.

```java
DssRestServiceRequest request = commandRequest.getService().makeRequest(commandRequest.getRequest());

response = method.invoke(exceptionHandler, request.getBody());
```

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java (hunk 1 above)
Comment (ztkmkoo) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestExceptionHandlerCommandRequest.java]: transient is a variables modifier used in serialization. At the time of serialization, if we don’t want to save value of a particular variable in a file, then we use transient keyword. When JVM comes across transient keyword, it ignores original value of the variable and save default value of that variable data type.


The code may be
``` java
public class DssRestExceptionHandlerCommandRequest implements DssRestExceptionHandlerCommand {
    private static final long serialVersionUID = 5752260184738368572L;

    private transient final DssRestActorService service;
```

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java (hunk 5 above)
Comment (ztkmkoo) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: Ok~
It looks better.

**Comment by ztkmkoo** [comment]
> 
> 
> [Coverage Status](https://coveralls.io/builds/33072623)
> 
> Coverage decreased (-6.9%) to 76.183% when pulling **[07884d9](https://github.com/ztkmkoo/dss/commit/07884d90214e7feb2c87a7dbbfb1ec217d29efe1) on Alencion:feature/115_exception_handler** into **[87398b2](https://github.com/ztkmkoo/dss/commit/87398b2af825fd16eea8603523326ae3f9abe657) on ztkmkoo:develop**.

@Alencion 
Please success the coveralls coverage~

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+import io.github.ztkmkoo.dss.core.exception.annotation.ServiceExceptionHandler;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import java.lang.reflect.Method;
+import java.util.HashMap;
+import java.util.Map;
+import java.util.Objects;
+
+public class DssRestExceptionHandler {
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java]: Hi,
The name of the class(`DssRestExceptionHandler`) looks implementing the DssExceptionHandler interface.

How bout change name to DssRestExceptionHanlderResolver or else?

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+    }
+
+    private ExceptionHandleMethod setExceptionHandleMethod(DssExceptionHandler dssExceptionHandler, Method method){
+        return request -> {
+            try {
+                return (DssRestServiceResponse) method.invoke(dssExceptionHandler, request.getBody());
+            } catch (Exception e) {
+                logger.error("exception handling error: ", e);
+            }
+            return null;
```
Comment (ztkmkoo) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java]: Why return null?
Should return UNKOWN ERROR OR SERVER INTERNAL ERROR i think.

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java (hunk 4 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActor.java]: Ok. I'll try logger.

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java (hunk 6 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java]: I agree with that. The DssRestExceptionHandlerResolver is good name.

Naming is the hardest thing in the world. 👍

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java (hunk 7 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java]: My mistake. I don't think about that.

Comment (ztkmkoo) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandler.java]: We(Me and @Alencion) decide to return null here.

File: dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java [hunk 8]
```diff
@@ -0,0 +1,128 @@
...
+                .addDssService(new MyService())
+                .addDssService(new YourService())
+                .addExceptionHandler(new GlobalExceptionHandler());
+
+        stopDssRestServerAfterActivated(dssRestServer, 10 ,15);
+
+        dssRestServer.start();
+
+        assertTrue(dssRestServer.isShutdown());
+    }
```
Comment (ztkmkoo) [inline dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java]: @Alencion 
This test looks a little bit strange. Could you tell me the detail?

File: dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActorTest.java [hunk 9]
```diff
@@ -0,0 +1,65 @@
...
+    @Test
+    void handleException() {
+        restExceptionHandlerActorRef.tell(DssRestExceptionHandlerCommandRequest
+                .builder()
+                .service(testService())
+                .request(commandRequest)
+                .exception(new Exception())
+                .build());
+
+        probe.expectMessageClass(DssRestChannelHandlerCommandResponse.class);
```
Comment (ztkmkoo) [inline dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActorTest.java]: Could you test more bout the response not only the expected class.
I think we can expect the status code in the response at leat.

File: dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java [hunk 10]
```diff
@@ -0,0 +1,54 @@
...
+                return null;
+            }
+
+            @ServiceExceptionHandler(service = TestService.class, exception = Exception.class)
+            public DssRestServiceResponse serviceExceptionHandleMethod(DssRestServiceActorCommandRequest request) {
+                return null;
+            }
+        });
+
+        assertFalse(dssRestExceptionHandlerResolver.getExceptionHandlerMap().isEmpty());
```
Comment (ztkmkoo) [inline dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java]: Can we expect the key contains in the map? Test more like
``` java
assertTrue(dssRestExceptionHandlerResolver.getExceptionHandlerMap().contains(TestService.class))
```

File: dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java (hunk 8 above)
Comment (Alencion) [reply dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java]: I want to test that the server operates well after addExceptionHandler is added.

File: dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java (hunk 10 above)
Comment (Alencion) [reply dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java]: I agree with that! I think that's a better test.

File: dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java (hunk 8 above)
Comment (ztkmkoo) [reply dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestExceptionHandlerTest.java]: Yap, i see.

But the Test class name is `DssRestExceptionHandlerTest.java`. 
I was mistaken that you test the `ExceptionHandler.java` interface.
You already test it in `DssRestServerTest.java` why test here?

File: dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java (hunk 10 above)
Comment (ztkmkoo) [reply dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolverTest.java]: Thank you so much

File: dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActorTest.java (hunk 9 above)
Comment (Alencion) [reply dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestExceptionHandlerActorTest.java]: Ok. I don't think about it.

I will add status code and channelid assertEquals.
```java
assertEquals(HttpResponseStatus.BAD_REQUEST.code(), response.getStatus().intValue());
assertEquals("test", response.getChannelId());
```

**Review by ztkmkoo — APPROVED** [review]
Thank you so much.

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolver.java [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+        Method[] methods = dssExceptionHandler.getClass().getMethods();
+        HashMap<Class<? extends Exception>, ExceptionHandleMethod> globalExceptionHandlerMap = new HashMap<>();
+
+        for (Method method : methods) {
+            if (method.isAnnotationPresent(ExceptionHandler.class)) {
+                ExceptionHandler annotation = method.getAnnotation(ExceptionHandler.class);
+
+                for (Class<? extends Exception> exception : annotation.exception()) {
+                    globalExceptionHandlerMap.put(exception, setExceptionHandleMethod(dssExceptionHandler, method));
+                }
```
Comment (Doyuni) [inline dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolver.java:43]: I'd like to share what my concern is. This is same case on lines 49~51 too.
If `setExceptionHandlerMethod()` return null, `cotainMethod()` method of `DssRestExceptionHandlerActor` class may be return true.
For example)
```java
Map<String, Integer> map = new HashMap<>();
map.put("hello", null);
System.out.println(map.containsKey("hello")); // true
```

So, I recommend that this code will be changed like below.
```java
for (Class<? extends Exception> exception : annotation.exception()) {
    ExceptionHandleMethod exceptionHandleMethod = setExceptionHandleMethod(dssExceptionHandler, method);
    
    if (Objects.nonNull(exceptionHandleMethod)) {
            globalExceptionHandlerMap.put(exception, exceptionHandleMethod);
    }
 }
```

**Review by Doyuni — APPROVED** [review]

File: dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolver.java (hunk 11 above)
Comment (Alencion) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolver.java:43]: Thank you for review!! @Doyuni 

I think this method can't return null.

The reasons are as follows:
setExceptionHandleMethod(dssExceptionHandler, method); is return new ExceptionHandleMethod instance. 
```java
    private ExceptionHandleMethod setExceptionHandleMethod(DssExceptionHandler dssExceptionHandler, Method method) {
        return request -> {
            try {
                method.setAccessible(true);
                return (DssRestServiceResponse) method.invoke(dssExceptionHandler, request);
            } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
                logger.error("exception handling method invoke error: ", e);
            } catch (Exception e) {
                logger.error("exception handling error: ", e);
            }
            return null;
        };
    }

    // it is same as the previous code.
    private ExceptionHandleMethod setExceptionHandleMethod(DssExceptionHandler dssExceptionHandler, Method method) {
        return new ExceptionHandleMethod() {
            @Override
            public DssRestServiceResponse handlingException(DssRestServiceActorCommandRequest request) {
                try {
                    method.setAccessible(true);
                    return (DssRestServiceResponse) method.invoke(dssExceptionHandler, request);
                } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
                    logger.error("exception handling method invoke error: ", e);
                } catch (Exception e) {
                    logger.error("exception handling error: ", e);
                }
                return null;
            }
        };
    }
```

So, i think it don't need null checking

Comment (Doyuni) [reply dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/handler/DssRestExceptionHandlerResolver.java:43]: Oh, I missed that point. 

Thank you for telling me.
